name: Build application

description: 'Build application via gradlew'

inputs:
  working_dir:
    required: true
    default: './'
    description: 'A directory where gradlew exists'

runs:
  using: composite

  steps:
    - name: Check whether gradlew exists
      shell: bash
      run: |
        if [ ! -f ${{ inputs.working_dir }}gradlew ]; then
          echo "No gradlew exists on working directory ${{ inputs.working_dir }}"
          exit 1
        fi

    - name: Change gradlew permission
      shell: bash
      run: chmod +x ${{ inputs.working_dir }}gradlew

    - name: Cache gradle
      uses: actions/cache@v4
      id: gradle-cache
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
#          ${{ inputs.working_dir }}.gradle/caches
#          ${{ inputs.working_dir }}.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build if no gradle cache exists
      if: steps.gradle-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "No gradle found via cache. Running gradlew build..."
        ${{ inputs.working_dir }}gradlew build -x test
