name: Store Secret

inputs:
  secret_from_repo:
    required: true
    type: string
    description: "A secret profile in application. ( secrets.??? )"
  file_dir:
    required: true
    type: string
    description: "./, ./"
  file_name:
    required: true
    type: string
    description: "secret.txt, application-prod.yml, etc"

runs:
  using: 'composite'
  steps:
    - name: Store secret
      env:
        SECRET: ${{ inputs.secret_from_repo }}
        FILE_DIR: ${{ inputs.file_dir }}
        FILE_PATH: ${{ inputs.file_dir }}/${{ inputs.file_name }}
      shell: bash
      run: |
        mkdir -p "$FILE_DIR"
        
        if [ -f "$FILE_PATH" ]; then
          exit 1
        fi
        
        echo "$SECRET" > "$FILE_PATH"
