
name: test reusable workflows

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-application-1:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/composite/utils/build-application

  sleep-30-sec:
    uses: ./.github/workflows/sleep.yml
    with:
      sec: 30

  build-application-2:
    needs: sleep-30-sec
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/composite/utils/build-application

  build-application-3:
    needs: build-application-1
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/workflows/composite/utils/build-application

  # what happens if i do this?
  build-application-4:
    uses: ./.github/workflows/composite/utils/build-application
