name: test reusable workflows

on:
  push:
    branches:
      - reusable-workflow-test

jobs:
  time:
    runs-on: ubuntu-latest
    outputs:
      now: ${{ steps.get-time.outputs.time }}

    steps:
      - name: Set timezone and get current time
        id: get-time
        run: |
          export TZ="Asia/Seoul"
          date_tag=$(date +'%Y%m%d-%H%M%S')
          echo "time=$date_tag" >> $GITHUB_OUTPUT

  prune:
    uses: ./.github/workflows/prune-dockers-on-server.yml
    with:
      container-name: 'test-server'
    secrets:
      server-address: ${{ secrets.TEST_SERVER_ADDRESS }}
      ssh-user: ${{ secrets.TEST_SERVER_DEV }}
      ssh-pw: ${{ secrets.TEST_SERVER_DEV_PW }}

  push:
    needs: time
    uses: ./.github/workflows/push-docker-image.yml
    with:
      tags: |
        ${{ needs.time.outputs.now }}
        ${{ github.sha }}
      docker-file-name: 'test-server.dockerfile'
      docker-file-dir: './'
      profile-name: 'test-server'
      property-postfix: 'properties'
    secrets:
      docker-id: ${{ secrets.DOCKER_ID }}
      docker-pw: ${{ secrets.DOCKER_PW }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      profile-context: ${{ secrets.TEST_PROFILE_CONTEXT }}

  run-docker-on-server:
    uses: ./.github/workflows/run-docker-on-server.yml
    needs:
      - prune
      - push
