
name: test reusable workflows

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  prune-dockers:
    uses: ./.github/workflows/prune-dockers-on-server.yml
    with:
      server-address: ${{ secrets.TEST_SERVER_ADDRESS }}
      ssh-pw: ${{ secrets.TEST_SERVER_USER }}
      ssh-user: ${{ secrets.TEST_SERVER_PW }}

  test-build-docker:
    uses: ./.github/workflows/push-docker-image.yml
    with:
      docker-id: ${{ secrets.DOCKER_ID }}
      docker-pw: ${{ secrets.DOCKER_PW }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      profile-context: ${{ secrets.TEST_PROFILE_CONTEXT }}
      profile-name: 'test-profile'
      property-postfix: 'properties'

  run-docker-on-server:
    uses: ./.github/workflows/run-docker-on-server.yml
    needs:
      - prune-dockers
      - test-build-docker
