name: test reusable workflows

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  prune-dockers:
    uses: ./.github/workflows/prune-dockers-on-server.yml
    with:
      container-name: 'test-server'
    secrets:
      server-address: ${{ secrets.TEST_SERVER_ADDRESS }}
      ssh-user: ${{ secrets.TEST_SERVER_DEV }}
      ssh-pw: ${{ secrets.TEST_SERVER_DEV_PW }}

  test-build-docker:
    uses: ./.github/workflows/push-docker-image.yml
    with:
      image-tag: '${{ github.sha }}'
      profile-name: 'test-profile'
      property-postfix: 'properties'
    secrets:
      docker-id: ${{ secrets.DOCKER_ID }}
      docker-pw: ${{ secrets.DOCKER_PW }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      profile-context: ${{ secrets.TEST_PROFILE_CONTEXT }}

  run-docker-on-server:
    uses: ./.github/workflows/run-docker-on-server.yml
    needs:
      - prune-dockers
      - test-build-docker
