name: test reusable workflows

on:
  push:
    branches:
      - reusable-workflow-test

jobs:

  prune:
    uses: ./.github/workflows/prune-dockers-on-server.yml
    with:
      container-name: 'test-server'
    secrets:
      server-address: ${{ secrets.TEST_SERVER_ADDRESS }}
      ssh-user: ${{ secrets.TEST_SERVER_DEV }}
      ssh-pw: ${{ secrets.TEST_SERVER_DEV_PW }}

  push:
    uses: ./.github/workflows/push-docker-image.yml
    with:
      tags: |
        ${{ github.sha }}
      docker-file-name: 'test-server.dockerfile'
      docker-file-dir: './'
      profile-name: 'test-server'
      property-postfix: 'properties'
    secrets:
      docker-id: ${{ secrets.DOCKER_ID }}
      docker-pw: ${{ secrets.DOCKER_PW }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      profile-context: ${{ secrets.TEST_PROFILE_CONTEXT }}

  time:
    uses: ./.github/workflows/get-current-time.yml

  echo:
    runs-on: ubuntu-latest
    needs: time

    steps:
      - run: echo "${{ needs.time.outputs.time }}"

  run-docker-on-server:
    uses: ./.github/workflows/run-docker-on-server.yml
    needs:
      - prune
      - push
