name: test reusable workflows

on:
  push:
    branches:
      - reusable-workflow-test

jobs:

  prune:
    uses: ./.github/workflows/prune-dockers-on-server.yml
    with:
      container-name: 'test-server'
    secrets:
      server-address: ${{ secrets.TEST_SERVER_ADDRESS }}
      ssh-user: ${{ secrets.TEST_SERVER_DEV }}
      ssh-pw: ${{ secrets.TEST_SERVER_DEV_PW }}

  push:
    uses: ./.github/workflows/push-docker-image.yml
    with:
      tags: |
        ${{ github.sha }}
      platforms: |
        linux/amd64
        linux/arm64
      docker-file-name: 'test-server.dockerfile'
      docker-file-dir: './'
      profile-name: 'test-server'
      property-postfix: 'properties'
    secrets:
      docker-repo: ${{ secrets.DOCKER_REPO }}
      docker-id: ${{ secrets.DOCKER_ID }}
      docker-pw: ${{ secrets.DOCKER_PW }}
      profile-context: ${{ secrets.TEST_PROFILE_CONTEXT }}

  run:
    needs:
      - prune
      - push
    uses: ./.github/workflows/run-docker-on-server.yml
    with:
      container-name: 'test-server'
      docker-image-tag: ${{ github.sha }}
      host-port: 8080
      profile-to-active: 'test-server'
    secrets:
      server-address: ${{ secrets.TEST_SERVER_ADDRESS }}
      ssh-user: ${{ secrets.TEST_SERVER_DEV }}
      ssh-pw: ${{ secrets.TEST_SERVER_DEV_PW }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      docker-id: ${{ secrets.DOCKER_ID }}
      docker-pw: ${{ secrets.DOCKER_PW }}
