name: test `create profiles` on pr

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create application-test-profile.properties from secret
        uses: ./.github/workflows/composite/utils/save-given-to-file
        with:
          arg: ${{ secrets.TEST_PROFILE_CONTEXT }}
          file_dir: './src/main/resources'
          file_name: 'application-test-profile.properties'

      - name: Show tree structure
        uses: ./.github/workflows/composite/utils/show-tree
        with:
          show_all: 'true'
          show_full_path: 'true'

      - name: Build application
        uses: ./.github/workflows/composite/utils/build-application
        with:
          working_dir: './'

      - name: Show tree structure
        uses: ./.github/workflows/composite/utils/show-tree
        with:
          show_all: 'true'
          show_full_path: 'true'
          working_dir: './src'
