name: test `create profiles` on pr

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: echo pwd & tree
        run: |
          echo $PWD
          tree -f

      - name: Create application-test-profile.properties from secret
        uses: ./.github/workflows/composite/create-profile/add-secret-profile
        with:
          secret_profile_context: ${{ secrets.TEST_PROFILE_CONTEXT }}
          resource_dir: 'src/main/resources'
          profile_name: 'test-profile'

      - name: echo pwd & tree
        run: |
          echo $PWD
          tree -f

      - name: upload test profile 1
        uses: actions/upload-artifact@v4
        with:
          name: 'test-profile-1'
          if-no-files-found: 'error'
          path: './src/main/resources/application-test-profile.properties'

      - name: Attempt to create duplicates
        id: check1
        uses: ./.github/workflows/composite/create-profile/add-secret-profile
        with:
          secret_profile_context: ${{ secrets.TEST_PROFILE_CONTEXT }}
          resource_dir: 'src/main/resources'
          profile_name: 'test-profile'
        continue-on-error: true

      - name: echo pwd & tree
        run: |
          echo $PWD
          tree -f

      - name: upload test profile 2
        uses: actions/upload-artifact@v4
        with:
          name: 'test-profile-2'
          if-no-files-found: 'error'
          path: './src/main/resources/application-test-profile.properties'
