name: Push docker image to DockerHub

on:
  workflow_call:
    inputs:
      docker-file-path:
        required: true
        type: string
        description: "A path of an dockerFile to build"

      profile-name:
        required: true
        type: string
        description: "A name of an profile to add"

      property-postfix:
        required: true
        type: string
        default: "properties"
        description: "A postfix to add to profile property like yml"

    secrets:
      profile-context:
        required: true
        description: "A context of profile to add"

      docker-repo:
        required: true
        description: "A name of docker repository to push"

      docker-id:
        required: true
        description: "DockerHub ID"

      docker-pw:
        required: true
        description: "DockerHub PW"


env:
  base-name: ${{ secrets.docker-id }}/${{ secrets.docker-repo }}
  file-path: ${{ inputs.docker-file-path }}
  user: ${{ secrets.docker-id }}
  pw: ${{ secrets.docker-pw }}

  context: ${{ secrets.profile-context }}
  property: 'application-${{ inputs.profile-name }}.${{ inputs.property-postfix }}'

jobs:
  push-docker-img:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add application profile
        uses: ./.github/workflows/composite/utils/save-given-to-file
        with:
          context: ${{ env.context }}
          file_dir: 'src/main/resources'
          file_name: ${{ env.property }}

      - name: Build application
        uses: ./.github/workflows/composite/utils/build-application

      - name: Show tree structure
        uses: ./.github/workflows/composite/utils/show-tree

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.user }}
          password: ${{ env.pw }}
          logout: 'true'

      - name: Show tree structure
        uses: ./.github/workflows/composite/utils/show-tree

      - name: Create docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.base-name }}
          tags: |
            type=ref,event=branch
            type=sha
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss', tz='Asia/Seoul'}}

      - name: Build and push image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: './'
          file: ${{ env.file-path }}
          push: 'true'
          tags: ${{ steps.meta.outputs.tags }}
